package main

// These numerics have been retrieved from:
//   http://defs.ircdocs.horse/ and http://modern.ircdocs.horse/
//
// They're intended to represent a relatively-standard cross-section of the IRC
// server ecosystem out there. Custom numerics will be marked as such.
const (
	RPLWelcome                     = "001"
	RPLYourhost                    = "002"
	RPLCreated                     = "003"
	RPLMyinfo                      = "004"
	RPLIsupport                    = "005"
	RPLSnomaskis                   = "008"
	RPLBounce                      = "010"
	RPLTracelink                   = "200"
	RPLTraceconnecting             = "201"
	RPLTracehandshake              = "202"
	RPLTraceunknown                = "203"
	RPLTraceoperator               = "204"
	RPLTraceuser                   = "205"
	RPLTraceserver                 = "206"
	RPLTraceservice                = "207"
	RPLTracenewtype                = "208"
	RPLTraceclass                  = "209"
	RPLTracereconnect              = "210"
	RPLStatslinkinfo               = "211"
	RPLStatscommands               = "212"
	RPLEndofstats                  = "219"
	RPLUmodeis                     = "221"
	RPLServlist                    = "234"
	RPLServlistend                 = "235"
	RPLStatsuptime                 = "242"
	RPLStatsoline                  = "243"
	RPLLuserclient                 = "251"
	RPLLuserop                     = "252"
	RPLLuserunknown                = "253"
	RPLLuserchannels               = "254"
	RPLLuserme                     = "255"
	RPLAdminme                     = "256"
	RPLAdminloc1                   = "257"
	RPLAdminloc2                   = "258"
	RPLAdminemail                  = "259"
	RPLTracelog                    = "261"
	RPLTraceend                    = "262"
	RPLTryagain                    = "263"
	RPLWhoiscertfp                 = "276"
	RPLAway                        = "301"
	RPLUserhost                    = "302"
	RPLIson                        = "303"
	RPLUnaway                      = "305"
	RPLNowaway                     = "306"
	RPLWhoisuser                   = "311"
	RPLWhoisserver                 = "312"
	RPLWhoisoperator               = "313"
	RPLWhowasuser                  = "314"
	RPLEndofwho                    = "315"
	RPLWhoisidle                   = "317"
	RPLEndofwhois                  = "318"
	RPLWhoischannels               = "319"
	RPLList                        = "322"
	RPLListend                     = "323"
	RPLChannelmodeis               = "324"
	RPLUniqopis                    = "325"
	RPLChannelcreated              = "329"
	RPLWhoisaccount                = "330"
	RPLNotopic                     = "331"
	RPLTopic                       = "332"
	RPLTopictime                   = "333"
	RPLWhoisbot                    = "335"
	RPLWhoisactually               = "338"
	RPLInviting                    = "341"
	RPLSummoning                   = "342"
	RPLInvitelist                  = "346"
	RPLEndofinvitelist             = "347"
	RPLExceptlist                  = "348"
	RPLEndofexceptlist             = "349"
	RPLVersion                     = "351"
	RPLWhoreply                    = "352"
	RPLNamreply                    = "353"
	RPLLinks                       = "364"
	RPLEndoflinks                  = "365"
	RPLEndofnames                  = "366"
	RPLBanlist                     = "367"
	RPLEndofbanlist                = "368"
	RPLEndofwhowas                 = "369"
	RPLInfo                        = "371"
	RPLMotd                        = "372"
	RPLEndofinfo                   = "374"
	RPLMotdstart                   = "375"
	RPLEndofmotd                   = "376"
	RPLYoureoper                   = "381"
	RPLRehashing                   = "382"
	RPLYoureservice                = "383"
	RPLTime                        = "391"
	RPLUsersstart                  = "392"
	RPLUsers                       = "393"
	RPLEndofusers                  = "394"
	RPLNousers                     = "395"
	ERRUnknownerror                = "400"
	ERRNosuchnick                  = "401"
	ERRNosuchserver                = "402"
	ERRNosuchchannel               = "403"
	ERRCannotsendtochan            = "404"
	ERRToomanychannels             = "405"
	ERRWasnosuchnick               = "406"
	ERRToomanytargets              = "407"
	ERRNosuchservice               = "408"
	ERRNoorigin                    = "409"
	ERRInvalidcapcmd               = "410"
	ERRNorecipient                 = "411"
	ERRNotexttosend                = "412"
	ERRNotoplevel                  = "413"
	ERRWildtoplevel                = "414"
	ERRBadmask                     = "415"
	ERRUnknowncommand              = "421"
	ERRNomotd                      = "422"
	ERRNoadmininfo                 = "423"
	ERRFileerror                   = "424"
	ERRNonicknamegiven             = "431"
	ERRErroneusnickname            = "432"
	ERRNicknameinuse               = "433"
	ERRNickcollision               = "436"
	ERRUnavailresource             = "437"
	ERRReg_unavailable             = "440"
	ERRUsernotinchannel            = "441"
	ERRNotonchannel                = "442"
	ERRUseronchannel               = "443"
	ERRNologin                     = "444"
	ERRSummondisabled              = "445"
	ERRUsersdisabled               = "446"
	ERRNotregistered               = "451"
	ERRNeedmoreparams              = "461"
	ERRAlreadyregistred            = "462"
	ERRNopermforhost               = "463"
	ERRPasswdmismatch              = "464"
	ERRYourebannedcreep            = "465"
	ERRYouwillbebanned             = "466"
	ERRKeyset                      = "467"
	ERRChannelisfull               = "471"
	ERRUnknownmode                 = "472"
	ERRInviteonlychan              = "473"
	ERRBannedfromchan              = "474"
	ERRBadchannelkey               = "475"
	ERRBadchanmask                 = "476"
	ERRNochanmodes                 = "477"
	ERRBanlistfull                 = "478"
	ERRNoprivileges                = "481"
	ERRChanoprivsneeded            = "482"
	ERRCantkillserver              = "483"
	ERRRestricted                  = "484"
	ERRUniqopprivsneeded           = "485"
	ERRNooperhost                  = "491"
	ERRUmodeunknownflag            = "501"
	ERRUsersdontmatch              = "502"
	ERRHelpnotfound                = "524"
	ERRCannotsendrp                = "573"
	RPLWhoissecure                 = "671"
	RPLYourlanguagesare            = "687"
	RPLWhoislanguage               = "690"
	RPLHelpstart                   = "704"
	RPLHelptxt                     = "705"
	RPLEndofhelp                   = "706"
	ERRNoprivs                     = "723"
	RPLMononline                   = "730"
	RPLMonoffline                  = "731"
	RPLMonlist                     = "732"
	RPLEndofmonlist                = "733"
	ERRMonlistfull                 = "734"
	RPLLoggedin                    = "900"
	RPLLoggedout                   = "901"
	ERRNicklocked                  = "902"
	RPLSaslsuccess                 = "903"
	ERRSaslfail                    = "904"
	ERRSasltoolong                 = "905"
	ERRSaslaborted                 = "906"
	ERRSaslalready                 = "907"
	RPLSaslmechs                   = "908"
	RPLRegistration_success        = "920"
	ERRAccount_already_exists      = "921"
	ERRReg_unspecified_error       = "922"
	RPLVerifysuccess               = "923"
	ERRAccount_already_verified    = "924"
	ERRAccount_invalid_verify_code = "925"
	RPLReg_verification_required   = "927"
	ERRReg_invalid_cred_type       = "928"
	ERRReg_invalid_callback        = "929"
	ERRToomanylanguages            = "981"
	ERRNolanguage                  = "982"

	// draft
	// numerics
	// these
	// haven't
	// been
	// assigned
	// actual
	// codes,
	// so
	// we
	// use
	// RPL_NONE's
	// code
	// (300),
	// since
	// RPL_NONE
	// is
	// intended
	// to
	// be
	// used
	// when
	// testing
	// /
	// debugging
	// /
	// etc
	// features.

	ERRCannotResume = "300"
)
